### ISSUE TITLE
404 on bullet and number list pages

### ISSUE THREAD

**Issue by Bloke** [textile/textile-lang-com-website#28]
There's a broken link to https://textile-lang.com/article/enhanced-lists from the [bulleted](https://www.textile-lang.com/doc/bulleted-unordered-lists) and [numbered](https://www.textile-lang.com/doc/numbered-lists) list pages.

**Comment by philwareham** [comment]
Ok thanks. I’ll fix Monday.

**Comment by philwareham** [comment]
Fixed. Thanks for the report.

**Comment by eliph** [comment]
Unfortunately, the page on enhanced lists is still missing and displays a large 404. This page explained how to apply attributes to individual list items or to the list itself. Please re-insert something like this:

When a class/ID/lang/style attribute is put on the very first item in the list, then the markup
will be applied to the container, i.e.:

    #(class#id) Item 1
    # Item 2
    # Item 3

Renders:

    <ol class="class" id="id">
      <li>Item 1</li>
      <li>Item 2</li>
      <li>Item 3</li>
    </ol>

But if you also wish to put a class on individual items in the list, you
simply make the first list item end with a ‘.’ dot immediately after the
attributes. That holds the ‘container’ modifiers, and then proceed as
normal. viz:

    #(class#id).
    #(first) Item 1
    #(second) Item 2
    #(third) Item 3

Gives:

    <ol class="class" id="id">
      <li class="first">Item 1</li>
      <li class="second">Item 2</li>
      <li class="third">Item 3</li>
    </ol>

You can put the class/ID/lang/style modifiers on any list item; this works for ordered,
unordered and definition lists.

**IMPORTANT**: *Due to the way the lists are processed, you need a ’.’
after the attributes of your ’empty’ list item to trigger the correct
behaviour.*

**Comment by philwareham** [comment]
I've now added the info above to the unordered and ordered lists documentation pages. Thanks!
